# Generated by Django 4.2 on 2023-12-08 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_childinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinfo',
            name='chest',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='foot',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='gender',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='height',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='hip',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='inseam',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='measurement',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='waist',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='weight',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
