# Generated by Django 4.2 on 2024-01-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_childinfo_chest_childinfo_first_name_childinfo_foot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish')], default='english', help_text='User language preference', max_length=20, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='chest',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='foot',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='height',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='hip',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='inseam',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='measurement',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='waist',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='weight',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
    ]
