# Generated by Django 4.2 on 2024-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_language_alter_childinfo_chest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('malay', 'Malay')], default='english', help_text='User language preference', max_length=20, verbose_name='language'),
        ),
    ]
