# Generated by Django 4.2 on 2024-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('description', models.CharField(max_length=200)),
                ('size_chart', models.JSONField()),
            ],
        ),
    ]
